CREATE TABLE orders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 order_id VARCHAR(40) UNIQUE NOT NULL, buyer VARCHAR(120) NOT NULL, style VARCHAR(160),
 quality VARCHAR(160), qty INT UNSIGNED NOT NULL, delivery_date DATE NULL,
 status VARCHAR(40) DEFAULT 'Pending', created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL
);