CREATE TABLE payments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_number VARCHAR(100) UNIQUE NOT NULL,
 amount DECIMAL(12,2) NOT NULL, payment_id VARCHAR(100) NULL, trx_id VARCHAR(100) NULL,
 status VARCHAR(50) DEFAULT 'PENDING', raw_response JSON NULL,
 created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL
);